# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
matrix:
  include:
    - os: linux
      julia: 0.7
    - os: linux
      julia: nightly
    - os: linux
      julia: 0.7
      env: "CMAKE_JL_BUILD_FROM_SOURCE=1"
    - os: linux
      julia: nightly
      env: "CMAKE_JL_BUILD_FROM_SOURCE=1"
    - os: osx
      julia: 0.7
    - os: osx
      julia: 0.7
      env: "CMAKE_JL_BUILD_FROM_SOURCE=1"
  # allow_failures:
  #   - julia: nightly
notifications:
  email: false
branches:
  only: master
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("CMake"); Pkg.test("CMake"; coverage=true)'
after_success:
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("CMake")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
